services:
  backend:
    image: backend-image
    container_name: hr-backend
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=postgres
      - DB_PASS=root123
      - DB_NAME=hrdb
      - DB_DIALECT=postgres
    networks:
      - hr-network

  frontend:
    image: frontend-image
    container_name: hr-frontend
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
networks:
  hr-network:
    driver: bridge