global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'node-backend'
    static_configs:
      - targets: ['backend:5000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # - job_name: 'jenkins'
  #   metrics_path: '/prometheus'
  #   static_configs:
  #     - targets: ['jenkins:8080']

